name: Release Electron App

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release
